name: frhodo
channels:
  - cantera/label/dev
  - conda-forge
  - defaults
dependencies:
  - cantera=2.5.0a3
  - matplotlib=3.1.2
  - nlopt=2.6.1
  - numpy=1.17.3
  - pip=19.3.1
  - pyside2=5.13.1
  - qtpy=1.9.0
  - scipy=1.3.1
  - tabulate=0.8.5
  - pip:
    - mplcairo==0.2